"""
MCP Server 3 - GitHub Pull Request Creator
Creates GitHub pull requests for prompt updates using GitHub REST API
"""
import json
import os
import base64
import ssl
import certifi
from typing import Dict, Any
from urllib import request, error
from datetime import datetime


# GitHub configuration from environment variables
GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')
GITHUB_REPO = os.environ.get('GITHUB_REPO', 'username/repo')
GITHUB_API_BASE = 'https://api.github.com'


def create_github_pr(prompt_text: str, reason: str) -> Dict[str, Any]:
    """
    Create a GitHub pull request with updated prompt
    
    Args:
        prompt_text: The updated prompt text
        reason: Reason for the update
        
    Returns:
        Dictionary with PR URL and status
    """
    if not GITHUB_TOKEN:
        return {
            'success': False,
            'error': 'GitHub token not configured'
        }
    
    try:
        # Parse repo owner and name
        repo_parts = GITHUB_REPO.split('/')
        if len(repo_parts) != 2:
            return {
                'success': False,
                'error': 'Invalid GITHUB_REPO format. Expected: owner/repo'
            }
        
        owner, repo = repo_parts
        
        # Generate branch name
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        branch_name = f'prompt-update-{timestamp}'
        
        # Create SSL context with certifi certificates
        ssl_context = ssl.create_default_context(cafile=certifi.where())
        
        # Step 1: Get default branch reference
        ref_url = f'{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs/heads/main'
        headers = {
            'Authorization': f'token {GITHUB_TOKEN}',
            'Accept': 'application/vnd.github.v3+json',
            'User-Agent': 'MCP-GitHub-Server'
        }
        
        req = request.Request(ref_url, headers=headers)
        with request.urlopen(req, context=ssl_context) as response:
            ref_data = json.loads(response.read().decode())
            base_sha = ref_data['object']['sha']
        
        # Step 2: Create new branch
        create_ref_url = f'{GITHUB_API_BASE}/repos/{owner}/{repo}/git/refs'
        ref_payload = {
            'ref': f'refs/heads/{branch_name}',
            'sha': base_sha
        }
        
        req = request.Request(
            create_ref_url,
            data=json.dumps(ref_payload).encode(),
            headers=headers,
            method='POST'
        )
        with request.urlopen(req, context=ssl_context) as response:
            pass  # Branch created
        
        # Step 3: Get current file content (if exists)
        file_path = 'prompts/system_prompt.txt'
        file_url = f'{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{file_path}'
        
        file_sha = None
        try:
            req = request.Request(file_url, headers=headers)
            with request.urlopen(req, context=ssl_context) as response:
                file_data = json.loads(response.read().decode())
                file_sha = file_data['sha']
        except error.HTTPError as e:
            if e.code != 404:
                raise
            # File doesn't exist, will create new
        
        # Step 4: Update or create file
        content_encoded = base64.b64encode(prompt_text.encode()).decode()
        file_payload = {
            'message': f'Update system prompt: {reason}',
            'content': content_encoded,
            'branch': branch_name
        }
        
        if file_sha:
            file_payload['sha'] = file_sha
        
        req = request.Request(
            file_url,
            data=json.dumps(file_payload).encode(),
            headers=headers,
            method='PUT'
        )
        with request.urlopen(req, context=ssl_context) as response:
            pass  # File updated
        
        # Step 5: Create pull request
        pr_url = f'{GITHUB_API_BASE}/repos/{owner}/{repo}/pulls'
        pr_payload = {
            'title': f'Update System Prompt - {reason}',
            'body': f'''## Prompt Update

**Reason:** {reason}

**Updated Prompt:**
```
{prompt_text}
```

This PR was automatically generated by the MCP GitHub Server based on evaluation results.
''',
            'head': branch_name,
            'base': 'main'
        }
        
        req = request.Request(
            pr_url,
            data=json.dumps(pr_payload).encode(),
            headers=headers,
            method='POST'
        )
        
        with request.urlopen(req, context=ssl_context) as response:
            pr_data = json.loads(response.read().decode())
            
            return {
                'success': True,
                'pr_url': pr_data['html_url'],
                'pr_number': pr_data['number'],
                'branch': branch_name
            }
            
    except error.HTTPError as e:
        error_body = e.read().decode() if e.fp else str(e)
        return {
            'success': False,
            'error': f'GitHub API error: {e.code} - {error_body}'
        }
    except Exception as e:
        return {
            'success': False,
            'error': f'Error creating PR: {str(e)}'
        }


def lambda_handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    AWS Lambda handler for GitHub PR creation
    
    Args:
        event: Lambda event object
        context: Lambda context object
        
    Returns:
        Response with PR details
    """
    try:
        # Parse request body
        body = {}
        if isinstance(event, dict):
            if 'body' in event:
                if isinstance(event['body'], str):
                    body = json.loads(event['body'])
                else:
                    body = event['body']
            elif 'prompt_text' in event:
                body = event
        
        # Get parameters
        prompt_text = body.get('prompt_text', '')
        reason = body.get('reason', 'Low evaluation scores detected')
        
        # Validate inputs
        if not prompt_text:
            return {
                'statusCode': 400,
                'headers': {
                    'Content-Type': 'application/json'
                },
                'body': json.dumps({
                    'error': 'prompt_text is required'
                })
            }
        
        # Create PR
        result = create_github_pr(prompt_text, reason)
        
        # Return response
        status_code = 200 if result.get('success') else 500
        
        return {
            'statusCode': status_code,
            'headers': {
                'Content-Type': 'application/json'
            },
            'body': json.dumps(result)
        }
        
    except Exception as e:
        # Return error response
        return {
            'statusCode': 500,
            'headers': {
                'Content-Type': 'application/json'
            },
            'body': json.dumps({
                'success': False,
                'error': str(e)
            })
        }


# For local testing
if __name__ == '__main__':
    print("Testing MCP GitHub Server")
    print("=" * 60)
    
    # Test PR creation
    test_event = {
        'prompt_text': '''You are a helpful AI assistant. Your goal is to provide accurate, 
complete, and helpful responses to user questions. Always:
- Be clear and concise
- Provide examples when helpful
- Admit when you don't know something
- Ask clarifying questions if needed''',
        'reason': 'Low evaluation scores detected in recent conversations'
    }
    
    print("\nTest: Create Pull Request")
    print(f"Reason: {test_event['reason']}")
    
    result = lambda_handler(test_event, None)
    response = json.loads(result['body'])
    
    print(f"\nStatus Code: {result['statusCode']}")
    print(f"Response: {json.dumps(response, indent=2)}")
    
    if response.get('success'):
        print(f"\n✓ PR Created Successfully!")
        print(f"  URL: {response['pr_url']}")
        print(f"  PR Number: {response['pr_number']}")
        print(f"  Branch: {response['branch']}")
    else:
        print(f"\n✗ Error: {response.get('error')}")
